name: tests

on:
  push:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: db
          POSTGRES_PASSWORD: db
          POSTGRES_DB: db_test
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: pdo, pgsql, pdo_pgsql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Copy environment file
        run: cp .env.github-actions .env

      - name: Run PHPUnit
        run: composer test
